### ISSUE TITLE
关于MDOAU-net文件中data文件夹下的train文件缺失问题

### ISSUE THREAD

**Issue by celin18** [Jichao-Wang/MDOAU-net#1]
请问MDOAU-net文件中data文件夹下的train文件是缺失了吗？这个在哪下载？

**Comment by Jichao-Wang** [comment]
我们不提供完整的训练数据集。训练集和测试集只提供文件结构框架和几个样例，大家可以自行代入自己的数据训练。

**Comment by Jichao-Wang** [comment]
但是训练集的文件结构的确缺失了，现已补上。
